FROM oven/bun:1-alpine AS build
WORKDIR /app

# Copy package files
COPY package.json bun.lock ./
RUN bun install --ignore-scripts

# Copy source code
COPY src ./src
COPY public ./public
COPY .env.stage ./.env
COPY tsconfig.* ./
COPY vite.config.ts ./
COPY index.html ./

RUN bun run build

FROM nginx:alpine
COPY --from=build /app /app
RUN rm -rf /usr/share/nginx/html/*
RUN cp -r /app/dist/* /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
