services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.stage
    container_name: mbos_stage_web
    env_file:
      - .env.stage
    networks:
      - stage_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=stage_net"
      - "traefik.http.routers.web.rule=Host(`web.mbos-online.uz`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "traefik.http.services.web.loadbalancer.server.port=80"
      - "traefik.http.middlewares.rate-limit.ratelimit.burst=20"
      - "traefik.http.middlewares.rate-limit.ratelimit.period=1s"
      - "traefik.http.middlewares.security-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.security-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.security-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.security-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.security-headers.headers.stsPreload=true"
      - "traefik.http.middlewares.security-headers.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.security-headers.headers.customResponseHeaders.X-Robots-Tag=noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
      - "traefik.http.middlewares.security-headers.headers.customResponseHeaders.Server="
    restart: unless-stopped

volumes:
  traefik_logs:
    driver: local
networks:
  stage_net:
    external: true
